# Generated by Django 3.1.3 on 2020-11-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='text',
            field=models.TextField(default='Text'),
        ),
    ]
