# Generated by Django 3.1.3 on 2020-11-17 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20201116_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='tourguide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('facebook_handle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='update',
            name='date_uploaded',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
    ]
