# Generated by Django 3.1.3 on 2020-11-18 06:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0004_auto_20201117_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date_uploaded',
            field=models.DateField(default=datetime.date(2020, 11, 18)),
        ),
        migrations.CreateModel(
            name='publichat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_sent', models.DateTimeField(default=datetime.date(2020, 11, 18))),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('message_status', models.CharField(default='UNREAD', max_length=20)),
                ('date_sent', models.DateTimeField(max_length=20)),
                ('sender', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
