# Generated by Django 3.1.3 on 2020-11-18 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20201118_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publichat',
            name='time_sent',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='publichat',
            name='user',
        ),
        migrations.AddField(
            model_name='publichat',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
