# Generated by Django 3.1.3 on 2020-11-18 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0009_auto_20201118_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='chat',
        ),
    ]
