# Generated by Django 3.1.3 on 2020-11-23 07:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0010_auto_20201118_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message_status',
        ),
        migrations.AddField(
            model_name='chat',
            name='message_read',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='update',
            name='date_uploaded',
            field=models.DateField(default=datetime.date(2020, 11, 23)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
