# Generated by Django 3.1.3 on 2020-11-25 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20201124_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='update',
            name='date_uploaded',
            field=models.DateField(default=datetime.date(2020, 11, 25)),
        ),
    ]
