# Generated by Django 3.1.3 on 2020-11-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20201125_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='subject',
            field=models.CharField(default='Subject', max_length=50),
        ),
    ]
